### ISSUE TITLE
uid/gid 99999 problem with user namespace remapping enabled

### ISSUE THREAD

**Issue by phoefflin** [RocketChat/Docker.Base.Image#6]
In setups with user namespace remapping enabled there's a default UID and GID range of 65536 available in the container namespace. The base image has hardcoded UID and GID 99999, when pulling this image on systems with enabled user namespace remapping, docker gives the error below:

    failed to register layer: Error processing tar file(exit status 1): Container ID 99999 cannot be mapped to a host ID

It is possible to configure  larger UID and GID ranges on linux side but since 65536 is the default value it would be nicer to move the hardcoded IDs to something below 65536 to make standard setups happy again. Is that possible?

Thanks

**Comment by geekgonecrazy** [comment]
Looks like this happened via: https://github.com/RocketChat/Docker.Base.Image/pull/5

@robbyoconnor any ideas on this?  Would using the max of 65536 solve the clashing?  Or could we use something even lower and avoid clashing?

**Comment by phoefflin** [comment]
Not sure what the clashing is about, but why not create system users with 'useradd -r' and 'grouadd -r'  and let the system handle UID and GID between SYS_UID_MIN and SYS_UID_MAX? Worst thing happening could be that the id values change between builds if the debian base image adds additional system users/groups but I even that shouldn't be problematic in general.

**Comment by robbyoconnor** [comment]
I've done this with other images I wrote...

**Comment by robbyoconnor** [comment]
The idea is that the uid shouldn't map to a user on the host

**Comment by phoefflin** [comment]
Problem was solved for us by switching to the official rocket.chat image (https://hub.docker.com/_/rocket.chat).

Thanks

**Comment by robbyoconnor** [comment]
Feel free to roll this back

**Comment by geekgonecrazy** [comment]
@robbyoconnor going to take a closer look.  Let's open back so we can investigate this further

**Comment by robbyoconnor** [comment]
If it's anything - the PR to the official image was rejected -- so I'm fine with it being rolled back -- No ego here :)

**Comment by robbyoconnor** [comment]
@geekgonecrazy No issue on my server! 
![image](https://cloud.githubusercontent.com/assets/23088/24321508/ac088638-1124-11e7-8ce0-66835b9afdd4.png)

As you can see UID `99999` works fine -- This is Ubuntu 16.04

**Comment by robbyoconnor** [comment]
@geekgonecrazy see #7

**Comment by phoefflin** [comment]
@robbyoconnor according to your top output you didn't have user namespace remapping enabled, that's why you didn't have issues with the high UID/GID i guess. dockerd needs to be startet with command line option '--userns-remap=default' for example to enable it (see [dockerd commandline reference](https://docs.docker.com/engine/reference/commandline/dockerd/#starting-the-daemon-with-user-namespaces-enabled)).

With #7 the problem should be fixed also with remapping enabled, but to be honest I still don't understand why to hardcode the ids in the first place, especially in an image which is most likely not dealing with any persistent data.

**Comment by geekgonecrazy** [comment]
Sorry for the delay.  Been a busy few weeks.  Taking a fresh look at this..  Hard coding the UID/GID is not something I see many images do.  In fact I don't see many using non root users. 

From what I can tell there actually isn't any security gained by using a none root user.  Since the user isn't actually being created on the host, when you do `ps aux` you're gonna be seeing the UID instead of the username here.  So there is no usability gain by using a custom user either from what I can tell.

Thoughts?

**Comment by robbyoconnor** [comment]
Feel free to roll this back...sorry for the issues I caused :(
